"""Central model inventory. Unknown upstream facts stay explicit, never guessed."""

from __future__ import annotations

from backend.models.reference.metadata import ExpectedFile as F
from backend.models.reference.metadata import ModelMetadata as M

_UPSTREAM = "See upstream model card"
_TORCH_BACKENDS = ("cpu", "cuda", "directml", "mps")
# Models with a minimum_vram_mb floor are rejected outright on the CPU backend by
# compatible_backend(), so listing "cpu" for them would advertise a capability the
# platform refuses. Use this for anything that declares a VRAM requirement.
_ACCELERATED_BACKENDS = ("cuda", "directml", "mps")
_BIREFNET_BACKENDS = ("cpu", "cuda", "mps")

REALESRGAN_X2_ARTIFACT = F(
    "RealESRGAN_x2plus.pth",
    size_bytes=67_061_725,
    sha256=("49fafd45f8fd7aa8d31ab2a22d14d91b536c34494a5cfe31eb5d89c2fa266abb"),
)
REALESRGAN_X4_ARTIFACT = F(
    "RealESRGAN_x4plus.pth",
    size_bytes=67_040_989,
    sha256=("4fa0d38905f75ac06eb49a7951b426670021be3018265fd191d2125df9d682f1"),
)

MODEL_REGISTRY: dict[str, M] = {
    item.id: item
    for item in (
        M(
            "birefnet",
            "BiRefNet",
            "Image and video background removal / matting",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet",
            "MIT",
            False,
            "backend/models/birefnet/birefnet",
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "birefnet-dynamic",
            "BiRefNet Dynamic",
            "Dynamic-resolution image and video background removal",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet_dynamic",
            "MIT",
            False,
            "backend/models/birefnet/dynamic",
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "birefnet-hr",
            "BiRefNet HR",
            "High-resolution image and video background removal",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet_HR",
            "MIT",
            False,
            "backend/models/birefnet/hr",
            minimum_ram_mb=6144,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "birefnet-hr-matting",
            "BiRefNet HR Matting",
            "High-resolution soft-alpha matting",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet_HR-matting",
            "MIT",
            False,
            "backend/models/birefnet/hr-matting",
            minimum_ram_mb=6144,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "birefnet-lite-2k",
            "BiRefNet Lite 2K",
            "Lower-memory 2K background removal",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet_lite-2K",
            "MIT",
            False,
            "backend/models/birefnet/lite-2k",
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "birefnet-matting",
            "BiRefNet Matting",
            "Trimap-free soft-alpha matting",
            "Transformers/PyTorch",
            "zhengpeng7/BiRefNet-matting",
            "MIT",
            False,
            "backend/models/birefnet/matting",
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            dtype="fp16/bf16/fp32",
            version="main",
        ),
        M(
            "sttn-auto",
            "STTN Auto",
            "Video/text inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/sttn-auto",
            (F("infer_model.pth"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=4096,
            compatible_backends=_ACCELERATED_BACKENDS,
            enabled_by_default=True,
        ),
        M(
            "sttn-detection",
            "STTN Detection",
            "Detected-text video inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/sttn-det",
            (F("sttn.pth"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=4096,
            compatible_backends=_ACCELERATED_BACKENDS,
        ),
        M(
            "lama",
            "LaMa",
            "Image/frame inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/big-lama",
            (F("big-lama.pt"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "propainter",
            "ProPainter",
            "Motion-aware video inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/propainter",
            (F("ProPainter.pth"), F("raft-things.pth"), F("recurrent_flow_completion.pth")),
            minimum_ram_mb=8192,
            minimum_vram_mb=8192,
            compatible_backends=_ACCELERATED_BACKENDS,
        ),
        M(
            "paddleocr-server",
            "PaddleOCR Server",
            "Text detection",
            "Paddle",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/V5/ch_det",
            (F("inference.pdiparams"), F("inference.json")),
            minimum_ram_mb=2048,
            compatible_backends=("cpu", "cuda"),
            enabled_by_default=True,
        ),
        M(
            "paddleocr-mobile",
            "PaddleOCR Mobile",
            "Fast text detection",
            "Paddle",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/V5/ch_det_fast",
            (F("inference.pdiparams"), F("inference.json")),
            minimum_ram_mb=1024,
            compatible_backends=("cpu", "cuda"),
        ),
        M(
            "realesrgan-x2",
            "Real-ESRGAN x2",
            "Image upscaling",
            "PyTorch",
            "https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.1",
            "BSD-3-Clause (source code); weight terms require provenance review",
            False,
            "backend/models/realesrgan",
            (REALESRGAN_X2_ARTIFACT,),
            expected_size_bytes=REALESRGAN_X2_ARTIFACT.size_bytes,
            minimum_ram_mb=2048,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
            version="v0.2.1",
        ),
        M(
            "realesrgan-x4",
            "Real-ESRGAN x4",
            "Image upscaling",
            "PyTorch",
            "https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.1.0",
            "BSD-3-Clause (source code); weight terms require provenance review",
            False,
            "backend/models/realesrgan",
            (REALESRGAN_X4_ARTIFACT,),
            expected_size_bytes=REALESRGAN_X4_ARTIFACT.size_bytes,
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
            version="v0.1.0",
        ),
        M(
            "supir",
            "SUPIR v0",
            "Diffusion-based photo-realistic image restoration and upscaling",
            "Isolated PyTorch/CUDA",
            "https://github.com/Fanghua-Yu/SUPIR",
            "SUPIR non-commercial use only",
            False,
            "models/supir",
            expected_size_bytes=75_161_927_680,
            minimum_ram_mb=32768,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            version="bda91af",
            dtype="fp16/bf16",
        ),
        M(
            "seedvr2-3b",
            "SeedVR2 3B",
            "One-step image and video restoration / upscaling",
            "Isolated PyTorch/CUDA",
            "ByteDance-Seed/SeedVR2-3B",
            "Apache-2.0",
            False,
            "models/seedvr2",
            expected_size_bytes=14_600_000_000,
            minimum_ram_mb=32768,
            minimum_vram_mb=24576,
            compatible_backends=("cuda",),
            version="e4de8c2",
            dtype="bf16",
        ),
        M(
            "seedvr2-7b",
            "SeedVR2 7B",
            "Higher-capacity one-step image and video restoration / upscaling",
            "Isolated PyTorch/CUDA",
            "ByteDance-Seed/SeedVR2-7B",
            "Apache-2.0",
            False,
            "models/seedvr2",
            expected_size_bytes=66_900_000_000,
            minimum_ram_mb=65536,
            minimum_vram_mb=49152,
            compatible_backends=("cuda",),
            version="e4de8c2",
            dtype="bf16",
        ),
        M(
            "mirnet",
            "MIRNet LOL",
            "Low-light restoration",
            "PyTorch",
            "swz30/MIRNet",
            _UPSTREAM,
            False,
            "backend/models/mirnet/MIRNet_LOL.pth",
            minimum_ram_mb=4096,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "sam3.1",
            "SAM 3.1",
            "Text- and click-prompted object segmentation (Object Multiplex)",
            "Isolated PyTorch/CUDA",
            "facebook/sam3.1",
            "SAM License; gated access",
            True,
            "models/sam3",
            minimum_ram_mb=8192,
            # 0, not a real VRAM floor: this model runs on CPU too (slower), so
            # it can't be gated GPU-only the way SUPIR/SeedVR2 are. The actual
            # GPU-path VRAM check is preflight_sam3() (tools/shared/memory.py),
            # run at job time, same split BiRefNet's catalog entries use.
            minimum_vram_mb=0,
            compatible_backends=_BIREFNET_BACKENDS,
            version="0.1.4",
            dtype="fp16/bf16",
        ),
        M(
            "flux",
            "FLUX.2 Klein",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-klein-*",
            _UPSTREAM,
            True,
            "backend/models/generate",
            minimum_ram_mb=16384,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
        M(
            "flux2-dev",
            "FLUX.2 Dev",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-dev",
            "FLUX Non-Commercial License; gated access",
            True,
            "backend/models/generate",
            minimum_ram_mb=65536,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
        M(
            "flux2-klein-9b-fp8",
            "FLUX.2 Klein 9B FP8",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-klein-9b-fp8",
            "FLUX Non-Commercial License; gated access",
            True,
            "backend/models/generate",
            minimum_ram_mb=32768,
            minimum_vram_mb=10000,
            compatible_backends=("cuda",),
            dtype="fp8/bf16",
        ),
        M(
            "qwen3-tts-customvoice",
            "Qwen3-TTS 1.7B (CustomVoice)",
            "Text-to-speech with 9 premium pre-defined voices",
            "Isolated PyTorch/CUDA",
            "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
            "Apache-2.0",
            False,
            "models/qwen3-tts/customvoice",
            expected_size_bytes=4_520_159_586,
            minimum_ram_mb=16384,
            minimum_vram_mb=16384,
            compatible_backends=("cuda",),
            version="0c0e305",
            dtype="bf16",
        ),
        M(
            "qwen-image",
            "Qwen-Image",
            "Image generation",
            "Diffusers/PyTorch",
            "Qwen/Qwen-Image",
            "Apache-2.0",
            False,
            "backend/models/generate",
            minimum_ram_mb=65536,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
    )
}


def get_model(model_id: str) -> M:
    try:
        return MODEL_REGISTRY[model_id]
    except KeyError as exc:
        raise KeyError(f"Unknown model ID: {model_id}") from exc
