import { useCallback, useEffect, useRef, useState } from "react";
import { Background, BackgroundVariant, Controls, MiniMap, ReactFlow, ReactFlowProvider, useReactFlow } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { ContextMenu } from "../components";
import { useDesktopStore } from "../state/desktopStore";
import { useEditorStore } from "../state/editorStore";
import { useToast } from "../components/ToastContext";
import { MidgardEdge } from "./MidgardEdge";
import { MidgardNode } from "../nodes/MidgardNode";
const nodeTypes = { midgard: MidgardNode }; const edgeTypes = { midgard: MidgardEdge };
function CanvasBody({ onAdd }) { const wrapper = useRef(null); const flow = useReactFlow(); const toast = useToast(); const nodes = useEditorStore(store=>store.nodes); const edges=useEditorStore(store=>store.edges); const groups=useEditorStore(store=>store.groups); const onNodesChange=useEditorStore(store=>store.onNodesChange); const onEdgesChange=useEditorStore(store=>store.onEdgesChange); const connect=useEditorStore(store=>store.connect); const addNode=useEditorStore(store=>store.addNode); const setViewport=useEditorStore(store=>store.setViewport); const minimap=useDesktopStore(store=>store.minimapVisible); const [menu,setMenu]=useState(null);
  useEffect(()=>{const fit=()=>void flow.fitView({padding:.18,duration:250});window.addEventListener("midgard:fit",fit);return()=>window.removeEventListener("midgard:fit",fit);},[flow]);
  const drop=useCallback(async event=>{event.preventDefault();const position=flow.screenToFlowPosition({x:event.clientX,y:event.clientY});const schemaId=event.dataTransfer.getData("application/x-midgard-node");if(schemaId){addNode(schemaId,position);return;}const files=[...event.dataTransfer.files];if(files.length&&window.midgardDesktop?.registerDroppedFiles){const grants=await window.midgardDesktop.registerDroppedFiles(files);grants.forEach((grant,index)=>{const video=/\.(mp4|mov|mkv|webm|avi)$/i.test(grant.name);const id=addNode(video?"midgard.input.video":"midgard.input.image",{x:position.x+index*28,y:position.y+index*28});if(id)useEditorStore.getState().updateNode(id,{parameters:{pathGrantId:grant.grantId}});});}},[addNode,flow]);
  return <div ref={wrapper} className="relative h-full w-full" onContextMenu={event=>{event.preventDefault();setMenu({x:event.clientX,y:event.clientY,position:flow.screenToFlowPosition({x:event.clientX,y:event.clientY})});}}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connection=>{const result=connect(connection);if(!result.valid)toast.push(result.reason,"error");}} isValidConnection={connection=>useEditorStore.getState().canConnect(connection).valid} onDrop={drop} onDragOver={event=>{event.preventDefault();event.dataTransfer.dropEffect="copy";}} onMoveEnd={(_,viewport)=>setViewport(viewport)} fitView snapToGrid snapGrid={[16,16]} selectionOnDrag panOnScroll deleteKeyCode={["Backspace","Delete"]} multiSelectionKeyCode="Shift" minZoom={.15} maxZoom={3} connectionRadius={26}>
    <Background variant={BackgroundVariant.Dots} gap={20} size={1} color="#2a3542"/><Controls showInteractive={false}/>{minimap&&<MiniMap pannable zoomable nodeColor="#2a3542" maskColor="rgba(11,15,20,.72)"/>}
    {groups.map(group=><div key={group.id} className="pointer-events-none absolute rounded-xl border border-dashed border-mg-accent/50 bg-mg-accent/5" style={{transform:`translate(${group.position.x}px,${group.position.y}px)`,width:group.width,height:group.height}}><span className="px-2 text-xs text-mg-accent">{group.label}</span></div>)}
  </ReactFlow><ContextMenu open={Boolean(menu)} x={menu?.x||0} y={menu?.y||0} onClose={()=>setMenu(null)} onSelect={id=>{if(id==="add")onAdd(menu.position);if(id==="fit")flow.fitView({padding:.18});if(id==="select")useEditorStore.getState().selectAll();if(id==="layout")useEditorStore.getState().autoLayout();}} items={[{id:"add",label:"Add node…"},{id:"select",label:"Select all",shortcut:"Ctrl+A"},{id:"fit",label:"Fit workflow",shortcut:"F"},{id:"layout",label:"Auto layout"}]}/></div>;
}
export function WorkflowCanvas(props){return <ReactFlowProvider><CanvasBody {...props}/></ReactFlowProvider>;}
