"""Central model inventory. Unknown upstream facts stay explicit, never guessed."""

from __future__ import annotations

from backend.models.metadata import ExpectedFile as F
from backend.models.metadata import ModelMetadata as M

_UPSTREAM = "See upstream model card"
_TORCH_BACKENDS = ("cpu", "cuda", "directml", "mps")

REALESRGAN_X2_ARTIFACT = F(
    "RealESRGAN_x2plus.pth",
    size_bytes=67_061_725,
    sha256=("49fafd45f8fd7aa8d31ab2a22d14d91b536c34494a5cfe31eb5d89c2fa266abb"),
)
REALESRGAN_X4_ARTIFACT = F(
    "RealESRGAN_x4plus.pth",
    size_bytes=67_040_989,
    sha256=("4fa0d38905f75ac06eb49a7951b426670021be3018265fd191d2125df9d682f1"),
)

MODEL_REGISTRY: dict[str, M] = {
    item.id: item
    for item in (
        M(
            "sttn-auto",
            "STTN Auto",
            "Video/text inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/sttn-auto",
            (F("infer_model.pth"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=4096,
            compatible_backends=_TORCH_BACKENDS,
            enabled_by_default=True,
        ),
        M(
            "sttn-detection",
            "STTN Detection",
            "Detected-text video inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/sttn-det",
            (F("sttn.pth"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=4096,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "lama",
            "LaMa",
            "Image/frame inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/big-lama",
            (F("big-lama.pt"),),
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "propainter",
            "ProPainter",
            "Motion-aware video inpainting",
            "PyTorch",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/propainter",
            (F("ProPainter.pth"), F("raft-things.pth"), F("recurrent_flow_completion.pth")),
            minimum_ram_mb=8192,
            minimum_vram_mb=8192,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "paddleocr-server",
            "PaddleOCR Server",
            "Text detection",
            "Paddle",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/V5/ch_det",
            (F("inference.pdiparams"), F("inference.json")),
            minimum_ram_mb=2048,
            compatible_backends=("cpu", "cuda"),
            enabled_by_default=True,
        ),
        M(
            "paddleocr-mobile",
            "PaddleOCR Mobile",
            "Fast text detection",
            "Paddle",
            "bundled",
            _UPSTREAM,
            False,
            "backend/models/V5/ch_det_fast",
            (F("inference.pdiparams"), F("inference.json")),
            minimum_ram_mb=1024,
            compatible_backends=("cpu", "cuda"),
        ),
        M(
            "rembg",
            "rembg model catalog",
            "Background removal",
            "ONNX Runtime",
            "rembg upstream catalog",
            _UPSTREAM,
            False,
            "~/.u2net",
            compatible_backends=("cpu", "cuda", "directml"),
        ),
        M(
            "realesrgan-x2",
            "Real-ESRGAN x2",
            "Image upscaling",
            "PyTorch",
            "https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.1",
            "BSD-3-Clause (source code); weight terms require provenance review",
            False,
            "backend/models/realesrgan",
            (REALESRGAN_X2_ARTIFACT,),
            expected_size_bytes=REALESRGAN_X2_ARTIFACT.size_bytes,
            minimum_ram_mb=2048,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
            version="v0.2.1",
        ),
        M(
            "realesrgan-x4",
            "Real-ESRGAN x4",
            "Image upscaling",
            "PyTorch",
            "https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.1.0",
            "BSD-3-Clause (source code); weight terms require provenance review",
            False,
            "backend/models/realesrgan",
            (REALESRGAN_X4_ARTIFACT,),
            expected_size_bytes=REALESRGAN_X4_ARTIFACT.size_bytes,
            minimum_ram_mb=4096,
            minimum_vram_mb=0,
            compatible_backends=_TORCH_BACKENDS,
            version="v0.1.0",
        ),
        M(
            "supir",
            "SUPIR v0",
            "Diffusion-based photo-realistic image restoration and upscaling",
            "Isolated PyTorch/CUDA",
            "https://github.com/Fanghua-Yu/SUPIR",
            "SUPIR non-commercial use only",
            False,
            "models/supir",
            expected_size_bytes=75_161_927_680,
            minimum_ram_mb=32768,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            version="bda91af",
            dtype="fp16/bf16",
        ),
        M(
            "mirnet",
            "MIRNet LOL",
            "Low-light restoration",
            "PyTorch",
            "swz30/MIRNet",
            _UPSTREAM,
            False,
            "backend/models/mirnet/MIRNet_LOL.pth",
            minimum_ram_mb=4096,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "sam2",
            "SAM2",
            "Object segmentation",
            "Transformers/PyTorch",
            "facebook/sam2-hiera-*",
            _UPSTREAM,
            False,
            "backend/models/select_object",
            minimum_ram_mb=8192,
            minimum_vram_mb=4500,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "grounding-dino",
            "Grounding DINO",
            "Text-guided object detection",
            "Transformers/PyTorch",
            "IDEA-Research/grounding-dino-*",
            "Apache-2.0 (verify selected revision)",
            False,
            "backend/models/select_object",
            minimum_ram_mb=8192,
            minimum_vram_mb=4500,
            compatible_backends=_TORCH_BACKENDS,
        ),
        M(
            "flux",
            "FLUX.2 Klein",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-klein-*",
            _UPSTREAM,
            True,
            "backend/models/generate",
            minimum_ram_mb=16384,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
        M(
            "flux2-dev",
            "FLUX.2 Dev",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-dev",
            "FLUX Non-Commercial License; gated access",
            True,
            "backend/models/generate",
            minimum_ram_mb=65536,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
        M(
            "flux2-klein-9b-fp8",
            "FLUX.2 Klein 9B FP8",
            "Image generation",
            "Diffusers/PyTorch",
            "black-forest-labs/FLUX.2-klein-9b-fp8",
            "FLUX Non-Commercial License; gated access",
            True,
            "backend/models/generate",
            minimum_ram_mb=32768,
            minimum_vram_mb=10000,
            compatible_backends=("cuda",),
            dtype="fp8/bf16",
        ),
        M(
            "qwen-image",
            "Qwen-Image",
            "Image generation",
            "Diffusers/PyTorch",
            "Qwen/Qwen-Image",
            "Apache-2.0",
            False,
            "backend/models/generate",
            minimum_ram_mb=65536,
            minimum_vram_mb=12000,
            compatible_backends=("cuda",),
            dtype="bf16",
        ),
    )
}


def get_model(model_id: str) -> M:
    try:
        return MODEL_REGISTRY[model_id]
    except KeyError as exc:
        raise KeyError(f"Unknown model ID: {model_id}") from exc
