import { useCallback, useEffect, useRef, useState } from "react";
import { Search } from "lucide-react";
import { api, connectEvents } from "./api/client";
import { Button, Dialog, EmptyState, ErrorBoundary, LoadingState, SearchInput, ToastProvider, useToast } from "./components";
import { BottomDrawer } from "./diagnostics/BottomDrawer";
import { WorkflowCanvas } from "./editor/WorkflowCanvas";
import { Inspector } from "./inspector/Inspector";
import { ModelsDialog } from "./models/ModelsDialog";
import { SettingsDialog } from "./settings/SettingsDialog";
import { useDesktopStore } from "./state/desktopStore";
import { useEditorStore } from "./state/editorStore";
import { useRunStore } from "./state/runStore";
import { useServerStore } from "./state/serverStore";
import { StatusBar } from "./app/StatusBar";
import { EditorToolbar } from "./workflow/EditorToolbar";
import { NodeLibrary } from "./workflow/NodeLibrary";
function EditorApp(){const recoveryChecked=useRef(false);const executeRef=useRef(null);const toast=useToast();const server=useServerStore();const layout=useDesktopStore();const editor=useEditorStore();const runStore=useRunStore();const [issues,setIssues]=useState([]);const [search,setSearch]=useState({open:false,query:"",position:null});const [zoom]=useState(1);
  useEffect(()=>{void useServerStore.getState().bootstrap();let disposed=false,stop;connectEvents(event=>{useServerStore.getState().handleEvent(event);useRunStore.getState().handleEvent(event);},value=>useRunStore.getState().setConnection(value)).then(value=>{if(disposed)value();else stop=value;});return()=>{disposed=true;stop?.();};},[]);
  useEffect(()=>{if(server.nodes.length)useEditorStore.getState().setDefinitions(server.nodes);},[server.nodes]);
  useEffect(()=>{if(!server.nodes.length||recoveryChecked.current)return;recoveryChecked.current=true;window.midgardDesktop?.recoverWorkflow().then(document=>{if(document&&confirm("Recover the last autosaved workflow?"))useEditorStore.getState().loadWorkflow(document);else if(document)void window.midgardDesktop?.clearRecovery();});},[server.nodes]);
  useEffect(()=>{const timer=setInterval(()=>{const state=useEditorStore.getState();if(state.dirty)void window.midgardDesktop?.autosaveWorkflow(state.serialize());},30000);return()=>clearInterval(timer);},[]);
  const validate=useCallback(async()=>{try{const result=await api("/api/workflows/validate",{method:"POST",body:JSON.stringify(useEditorStore.getState().serialize())});setIssues(result.issues||[]);layout.setValue("drawerTab","problems");if(result.valid)toast.push("Workflow is valid");else{layout.setValue("drawerVisible",true);toast.push(`${result.issues.length} workflow problem(s)`,"error");}return result.valid;}catch(error){toast.push(error.message,"error");return false;}},[layout,toast]);
  const actions={newWorkflow:async()=>{if(editor.dirty&&!confirm("Discard unsaved workflow changes?"))return;const doc=await window.midgardDesktop?.newWorkflow();editor.newWorkflow(doc);setIssues([]);},openWorkflow:async()=>{const result=await window.midgardDesktop?.openWorkflow();if(result)editor.loadWorkflow(result.document);},saveWorkflow:async()=>{const result=await window.midgardDesktop?.saveWorkflow(editor.serialize());if(result){editor.markSaved();toast.push(`Saved ${result.name}`);}},validate,run:async()=>{if(await validate()){try{const run=await runStore.start(editor.serialize());window.midgardDesktop?.setRunProgress((run.progress||0)/100);toast.push("Workflow run started");}catch(error){toast.push(error.message,"error");}}}};
  executeRef.current=command=>{const e=useEditorStore.getState(),d=useDesktopStore.getState();const handlers={"workflow:new":actions.newWorkflow,"workflow:open":actions.openWorkflow,"workflow:save":actions.saveWorkflow,"workflow:save-as":async()=>{const result=await window.midgardDesktop?.saveWorkflowAs(e.serialize());if(result)e.markSaved();},"edit:undo":e.undo,"edit:redo":e.redo,"edit:copy":e.copySelected,"edit:paste":e.paste,"edit:duplicate":e.duplicateSelected,"edit:delete":e.deleteSelected,"edit:select-all":e.selectAll,"edit:deselect":e.deselect,"node:group":e.groupSelected,"node:auto-layout":e.autoLayout,"node:search":()=>setSearch({open:true,query:"",position:null}),"view:fit":()=>window.dispatchEvent(new Event("midgard:fit")),"view:library":()=>d.toggle("libraryVisible"),"view:inspector":()=>d.toggle("inspectorVisible"),"view:minimap":()=>d.toggle("minimapVisible"),"view:logs":()=>d.toggle("drawerVisible"),"view:downloads":()=>{d.setValue("drawerVisible",true);d.setValue("drawerTab","downloads");},"view:diagnostics":()=>{d.setValue("drawerVisible",true);d.setValue("drawerTab","diagnostics");},"view:settings":()=>d.setValue("settingsOpen",true),"view:models":()=>d.setValue("modelsOpen",true),"view:reset-layout":d.reset,"run:validate":validate,"run:start":actions.run,"run:pause":runStore.pause,"run:resume":runStore.resume,"run:stop":runStore.cancel,"run:clear-cache":runStore.clearCache,"models:refresh":server.refreshModels,"models:release":()=>api("/api/system/release-models",{method:"POST"})};handlers[command]?.();};
  useEffect(()=>window.midgardDesktop?.onMenuCommand(command=>executeRef.current?.(command)),[]);
  useEffect(()=>{function key(event){if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;if(event.key==="Tab"){event.preventDefault();setSearch({open:true,query:"",position:null});}if(event.key.toLowerCase()==="f")window.dispatchEvent(new Event("midgard:fit"));}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
  if(server.loading&&!server.nodes.length)return <LoadingState label="Connecting to Midgard control plane…"/>;if(server.error)return <EmptyState title="Backend connection failed" description={server.error} action={<Button onClick={()=>void server.bootstrap()}>Retry</Button>}/>;
  const filtered=server.nodes.filter(node=>`${node.name} ${node.category}`.toLowerCase().includes(search.query.toLowerCase())).slice(0,30);
  return <div className="grid h-full grid-rows-[3rem_minmax(0,1fr)_1.75rem]"><EditorToolbar actions={actions}/><main className="grid min-h-0" style={{gridTemplateColumns:`${layout.libraryVisible?`${layout.libraryWidth}px`:"0px"} minmax(0,1fr) ${layout.inspectorVisible?`${layout.inspectorWidth}px`:"0px"}`,gridTemplateRows:`minmax(0,1fr) ${layout.drawerVisible?`${layout.drawerHeight}px`:"0px"}`}}>{layout.libraryVisible&&<NodeLibrary onAdd={schemaId=>editor.addNode(schemaId)}/>}<WorkflowCanvas onAdd={position=>setSearch({open:true,query:"",position})}/>{layout.inspectorVisible&&<Inspector issues={issues} onRunNode={()=>void actions.run()}/>} {layout.drawerVisible&&<div className="col-span-3 min-h-0"><BottomDrawer issues={issues}/></div>}</main><StatusBar zoom={zoom}/>
  <Dialog open={search.open} onClose={()=>setSearch(value=>({...value,open:false}))} title="Add a node" description="Search the backend-owned node catalog."><SearchInput autoFocus value={search.query} onChange={query=>setSearch(value=>({...value,query}))}/><div className="mt-3 grid max-h-80 gap-1 overflow-auto">{filtered.map(node=><button key={node.schemaId} type="button" onClick={()=>{editor.addNode(node.schemaId,search.position||undefined);setSearch(value=>({...value,open:false}));}} className="flex min-h-11 items-center gap-3 rounded-lg px-3 text-left hover:bg-mg-selected focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mg-focus"><Search className="size-4 text-mg-secondary"/><span><strong className="block text-sm">{node.name}</strong><span className="text-xs text-mg-secondary">{node.category}</span></span></button>)}</div></Dialog><SettingsDialog/><ModelsDialog/></div>;
}
export default function App(){return <ErrorBoundary><ToastProvider><EditorApp/></ToastProvider></ErrorBoundary>;}
