import { create } from "zustand";
import { addEdge, applyEdgeChanges, applyNodeChanges } from "@xyflow/react";
const MAX_HISTORY = 100;
let clipboard = { nodes: [], edges: [] };
const snap = state => ({ nodes: structuredClone(state.nodes), edges: structuredClone(state.edges), groups: structuredClone(state.groups) });
const history = (state, patch) => ({ ...patch, past: [...state.past.slice(-(MAX_HISTORY - 1)), snap(state)], future: [], dirty: true });
const definitionsById = definitions => Object.fromEntries(definitions.map(value => [value.schemaId, value]));
const defaults = definition => Object.fromEntries(definition.parameters.map(parameter => [parameter.id, structuredClone(parameter.default)]));
function createNode(definition, position) { return { id: crypto.randomUUID(), type: "midgard", position, data: { schemaId: definition.schemaId, schemaVersion: definition.schemaVersion, label: definition.name, parameters: defaults(definition), definition }, selected: false }; }
function projectTemplate() { const now = new Date().toISOString(); return { format: "midgard-workflow", version: 1, projectId: crypto.randomUUID(), name: "Untitled workflow", createdAt: now, updatedAt: now, projectSettings: {}, viewport: { x: 0, y: 0, zoom: 1 }, metadata: {} }; }
export const useEditorStore = create((set, get) => ({
  nodes: [], edges: [], groups: [], past: [], future: [], dirty: false, project: projectTemplate(), definitions: [],
  setDefinitions: definitions => set({ definitions }),
  addNode: (schemaId, position = { x: 120, y: 120 }) => { const definition = get().definitions.find(value => value.schemaId === schemaId); if (!definition) return null; const node = createNode(definition, position); set(state => history(state, { nodes: [...state.nodes.map(value => ({ ...value, selected: false })), { ...node, selected: true }] })); return node.id; },
  onNodesChange: changes => set(state => { const changed = applyNodeChanges(changes, state.nodes); const permanent = changes.some(change => change.type === "remove"); return permanent ? history(state, { nodes: changed, edges: state.edges.filter(edge => changed.some(node => node.id === edge.source) && changed.some(node => node.id === edge.target)) }) : { nodes: changed, dirty: state.dirty || changes.some(change => change.type === "position") }; }),
  onEdgesChange: changes => set(state => history(state, { edges: applyEdgeChanges(changes, state.edges) })),
  canConnect: connection => { const state = get(); const map = definitionsById(state.definitions); const source = state.nodes.find(node => node.id === connection.source); const target = state.nodes.find(node => node.id === connection.target); if (!source || !target || source.id === target.id) return { valid: false, reason: "Connections require two different nodes." }; const sourcePort = map[source.data.schemaId]?.outputs.find(port => port.id === connection.sourceHandle); const targetPort = map[target.data.schemaId]?.inputs.find(port => port.id === connection.targetHandle); if (!sourcePort || !targetPort) return { valid: false, reason: "The selected port no longer exists." }; if (!(sourcePort.type === targetPort.type || (sourcePort.type === "INTEGER" && targetPort.type === "NUMBER"))) return { valid: false, reason: `${sourcePort.type} cannot connect to ${targetPort.type}.` }; if (state.edges.some(edge => edge.target === target.id && edge.targetHandle === targetPort.id)) return { valid: false, reason: `${targetPort.label} already has a connection.` }; return { valid: true, reason: "" }; },
  connect: connection => { const result = get().canConnect(connection); if (!result.valid) return result; set(state => history(state, { edges: addEdge({ ...connection, id: crypto.randomUUID(), type: "midgard" }, state.edges) })); return result; },
  removeEdge: id => set(state => history(state, { edges: state.edges.filter(edge => edge.id !== id) })),
  updateNode: (id, patch) => set(state => history(state, { nodes: state.nodes.map(node => node.id === id ? { ...node, data: { ...node.data, ...patch, parameters: patch.parameters ?? node.data.parameters } } : node) })),
  selectAll: () => set(state => ({ nodes: state.nodes.map(node => ({ ...node, selected: true })), edges: state.edges })),
  deselect: () => set(state => ({ nodes: state.nodes.map(node => ({ ...node, selected: false })), edges: state.edges.map(edge => ({ ...edge, selected: false })) })),
  deleteSelected: () => set(state => { const ids = new Set(state.nodes.filter(node => node.selected).map(node => node.id)); if (!ids.size && !state.edges.some(edge => edge.selected)) return state; return history(state, { nodes: state.nodes.filter(node => !ids.has(node.id)), edges: state.edges.filter(edge => !edge.selected && !ids.has(edge.source) && !ids.has(edge.target)) }); }),
  copySelected: () => { const state = get(); const ids = new Set(state.nodes.filter(node => node.selected).map(node => node.id)); clipboard = { nodes: structuredClone(state.nodes.filter(node => ids.has(node.id))), edges: structuredClone(state.edges.filter(edge => ids.has(edge.source) && ids.has(edge.target))) }; },
  duplicateSelected: () => { get().copySelected(); get().paste(); },
  paste: () => set(state => { if (!clipboard.nodes.length) return state; const ids = new Map(clipboard.nodes.map(node => [node.id, crypto.randomUUID()])); const nodes = clipboard.nodes.map(node => ({ ...structuredClone(node), id: ids.get(node.id), position: { x: node.position.x + 32, y: node.position.y + 32 }, selected: true })); const edges = clipboard.edges.map(edge => ({ ...structuredClone(edge), id: crypto.randomUUID(), source: ids.get(edge.source), target: ids.get(edge.target), selected: false })); clipboard = { nodes: structuredClone(nodes), edges: structuredClone(edges) }; return history(state, { nodes: [...state.nodes.map(node => ({ ...node, selected: false })), ...nodes], edges: [...state.edges, ...edges] }); }),
  groupSelected: () => set(state => { const ids = state.nodes.filter(node => node.selected).map(node => node.id); if (!ids.length) return state; const group = { id: crypto.randomUUID(), label: "Group", nodeIds: ids, position: { x: Math.min(...state.nodes.filter(n => ids.includes(n.id)).map(n => n.position.x)) - 40, y: Math.min(...state.nodes.filter(n => ids.includes(n.id)).map(n => n.position.y)) - 60 }, width: 420, height: 300, color: "accent" }; return history(state, { groups: [...state.groups, group] }); }),
  autoLayout: () => set(state => history(state, { nodes: state.nodes.map((node, index) => ({ ...node, position: { x: (index % 4) * 330, y: Math.floor(index / 4) * 240 } })) })),
  undo: () => set(state => { if (!state.past.length) return state; const previous = state.past.at(-1); return { ...previous, past: state.past.slice(0, -1), future: [snap(state), ...state.future], dirty: true }; }),
  redo: () => set(state => { if (!state.future.length) return state; const next = state.future[0]; return { ...next, past: [...state.past, snap(state)], future: state.future.slice(1), dirty: true }; }),
  markSaved: () => set({ dirty: false }), setViewport: viewport => set(state => ({ project: { ...state.project, viewport } })), setProjectName: name => set(state => ({ project: { ...state.project, name }, dirty: true })),
  newWorkflow: document => set({ nodes: [], edges: [], groups: [], past: [], future: [], dirty: false, project: document || projectTemplate() }),
  loadWorkflow: (document, definitions = get().definitions) => { const map = definitionsById(definitions); set({ project: { ...document, nodes: undefined, edges: undefined, groups: undefined }, nodes: document.nodes.map(node => ({ id: node.id, type: "midgard", position: node.position, data: { schemaId: node.schemaId, schemaVersion: node.schemaVersion, label: node.label || map[node.schemaId]?.name || node.schemaId, parameters: node.parameters || {}, definition: map[node.schemaId], disabled: node.disabled, bypass: node.bypass, collapsed: node.collapsed } })), edges: document.edges.map(edge => ({ id: edge.id, source: edge.sourceNodeId, sourceHandle: edge.sourcePortId, target: edge.targetNodeId, targetHandle: edge.targetPortId, type: "midgard" })), groups: document.groups || [], past: [], future: [], dirty: false }); },
  serialize: () => { const state = get(); return { ...state.project, updatedAt: new Date().toISOString(), nodes: state.nodes.map(node => ({ id: node.id, schemaId: node.data.schemaId, schemaVersion: node.data.schemaVersion, label: node.data.label, position: node.position, parameters: node.data.parameters || {}, disabled: Boolean(node.data.disabled), bypass: Boolean(node.data.bypass), collapsed: Boolean(node.data.collapsed) })), edges: state.edges.map(edge => ({ id: edge.id, sourceNodeId: edge.source, sourcePortId: edge.sourceHandle, targetNodeId: edge.target, targetPortId: edge.targetHandle })), groups: state.groups }; },
}));
