name: Build Windows CPU

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: false

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: Read VERSION
      id: version
      run: |
        VERSION=$(sed -n 's/^VERSION = "\(.*\)"/\1/p' backend/config.py)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
    # - name: Check if tag already exists
    #   run: |
    #     TAG_NAME="${VERSION}"
    #     if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
    #       echo "Tag $TAG_NAME already exists; aborting release"
    #       exit 1
    #     fi
    #   shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' # caching pip dependencies
    - name: Disable hardware acceleration
      run: sed -i 's/HARDWARE_ACCELERATION_OPTION *= *.*/HARDWARE_ACCELERATION_OPTION = False/g' backend/config.py
      shell: bash
    - run: pip install paddlepaddle==3.0.0
    - run: pip install torch==2.7.0 torchvision==0.22.0
    - run: pip install -r requirements.txt
    - run: pip freeze > requirements.txt
    - run: pip install QPT==1.0b8 setuptools
    - name: Get site-packages path
      shell: bash
      run: |
        SITE_PACKAGES=$(python -c "import site, os; print(os.path.join(site.getsitepackages()[0], 'Lib', 'site-packages'))")
        SITE_PACKAGES_UNIX=$(cygpath -u "$SITE_PACKAGES")
        echo "site-packages path: $SITE_PACKAGES"
        echo "site-packages UNIX path: $SITE_PACKAGES_UNIX"
        echo "SITE_PACKAGES_UNIX=$SITE_PACKAGES_UNIX" >> $GITHUB_ENV
        echo "SITE_PACKAGES=$SITE_PACKAGES" >> $GITHUB_ENV
    - name: Fix QPT internal error
      run: sed -i '98c\        try:\n            dep = pkg.requires()\n        except TypeError:\n            continue' ${SITE_PACKAGES_UNIX}/qpt/kernel/qpackage.py
      shell: bash
    - name: Start SSH via tmate
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      uses: mxschmitt/action-tmate@v3
    - run: |
        python backend/tools/makedist.py && \
        mv ../midgard_out ./midgard_out && \
        cp ./midgard_out/Debug/Debug-*.cmd ./midgard_out/Release/ && \
        sed -i 's/force=False)/force=False)\n            exit(-1)/g' ./midgard_out/*/Python/Lib/site-packages/qpt/executor.py
      env:
        QPT_Action: "True"
      shell: bash
    - name: Upload Debug folder to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: midgard-v${{ env.VERSION }}-windows-cpu-debug
        path: midgard_out/Debug/
    - name: Upload Release folder to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: midgard-v${{ env.VERSION }}-windows-cpu-release
        path: midgard_out/Release/
    - name: Package Release folder
      run: |
        cd midgard_out/Release
        7z a -t7z -mx=9 -m0=LZMA2 -ms=on -mfb=64 -md=32m -mmt=on -v2000m midgard-v${{ env.VERSION }}-windows-cpu.7z * && \
        # Check if there is only one volume
        if [ -f midgard-v${{ env.VERSION }}-windows-cpu.7z.001 ] && [ ! -f midgard-v${{ env.VERSION }}-windows-cpu.7z.002 ]; then \
          mv midgard-v${{ env.VERSION }}-windows-cpu.7z.001 midgard-v${{ env.VERSION }}-windows-cpu.7z; fi
      shell: bash
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.VERSION }}
        target_commitish: ${{ github.sha }}
        name: Hard Subtitle Remover v${{ env.VERSION }}
        files: |
          midgard_out/Release/midgard-v${{ env.VERSION }}-windows-cpu.7z*